"""API v1 request/response schemas — HR & payroll (HR-BE-002)."""

from core.api.v1.schemas.hr import (
    DepartmentCreate,
    DepartmentOut,
    DepartmentUpdate,
    EmployeeCreate,
    EmployeeOut,
    EmployeeStatusBody,
    EmployeeUpdate,
    LeaveAccrueRequest,
    LeaveBalanceAdjustRequest,
    LeaveBalanceOut,
    LeaveMovementOut,
    LeaveRequestCreate,
    LeaveRequestOut,
    LeaveRequestRejectBody,
    TerminateRequest,
)
from core.api.v1.schemas.payroll import (
    CompensationCreate,
    CompensationOut,
    EntryAdjustmentIn,
    MoneyOut,
    PayrollEntryOut,
    PayrollRunCreate,
    PayrollRunOut,
    PayrollSettingsIn,
    PayrollSettingsOut,
    RunComputeOut,
    SkippedEmployeeOut,
)

__all__ = [
    "CompensationCreate",
    "CompensationOut",
    "DepartmentCreate",
    "DepartmentOut",
    "DepartmentUpdate",
    "EmployeeCreate",
    "EmployeeOut",
    "EmployeeStatusBody",
    "EmployeeUpdate",
    "EntryAdjustmentIn",
    "LeaveAccrueRequest",
    "LeaveBalanceAdjustRequest",
    "LeaveBalanceOut",
    "LeaveMovementOut",
    "LeaveRequestCreate",
    "LeaveRequestOut",
    "LeaveRequestRejectBody",
    "MoneyOut",
    "PayrollEntryOut",
    "PayrollRunCreate",
    "PayrollRunOut",
    "PayrollSettingsIn",
    "PayrollSettingsOut",
    "RunComputeOut",
    "SkippedEmployeeOut",
    "TerminateRequest",
]
