"""ai_follow_up_suggestions - one generated follow-up for a CRM entity (SKY-61).

Generated by the hourly follow-up scan (per user, for the entities they own),
then transitioned ``pending -> sent | dismissed | expired`` by a human one-click
Apply (which creates a real CRM activity via core and records the applied_by
actor + created activity id here for the audit trail). ``expires_at`` is a
required application-set timestamp (7 days by convention) that drives the
expiry sweep job.

``entity_type``/``entity_id`` soft-link to any CRM entity (lead, opportunity,
customer, contact) - the CRM rows are owned by core. ``user_id`` references an
identity user (the actor the suggestion is generated for). ``activity_id`` is
filled when a follow-up is applied (the created CRM activity), a plain UUID.
"""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import (
    CheckConstraint,
    DateTime,
    ForeignKey,
    Index,
    String,
    Text,
    func,
    text,
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from ai_agent.models.base import Base


class AiFollowUpSuggestionModel(Base):
    """One generated follow-up suggestion pending a human apply/dismiss."""

    __tablename__ = "ai_follow_up_suggestions"
    __table_args__ = (
        CheckConstraint(
            "entity_type IN ('lead', 'opportunity', 'customer', 'contact')",
            name="ck_ai_follow_up_entity_type",
        ),
        CheckConstraint(
            "suggestion_type IN ('email', 'call', 'meeting', 'task')",
            name="ck_ai_follow_up_type",
        ),
        CheckConstraint(
            "status IN ('pending', 'sent', 'dismissed', 'expired')",
            name="ck_ai_follow_up_status",
        ),
        CheckConstraint(
            "confidence >= 0 AND confidence <= 1", name="ck_ai_follow_up_confidence_range"
        ),
        Index("idx_follow_up_tenant_user", "tenant_id", "user_id", "status"),
        Index("idx_follow_up_entity", "tenant_id", "entity_type", "entity_id"),
    )

    tenant_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("tenants.id", ondelete="CASCADE"),
        primary_key=True,
        nullable=False,
    )
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, nullable=False
    )
    user_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False)
    entity_type: Mapped[str] = mapped_column(String(32), nullable=False)
    entity_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False)
    suggestion_type: Mapped[str] = mapped_column(
        String(16), nullable=False, server_default=text("'task'")
    )
    draft_content: Mapped[str] = mapped_column(Text, nullable=False)
    reasoning: Mapped[str] = mapped_column(Text, nullable=False)
    confidence: Mapped[float] = mapped_column(nullable=False, server_default=text("0"))
    status: Mapped[str] = mapped_column(
        String(16), nullable=False, server_default=text("'pending'")
    )
    sent_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    applied_by: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)
    activity_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )
    expires_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
