"""ai_rag_chunks - child chunks (~400 tokens, embedded, searched).

Child chunks are the searchable units: each carries a 768-dimension pgvector
embedding generated by the configured model (default: OpenAI
``text-embedding-3-small`` at 768d, or local ``nomic-embed-text`` - both emit
768-dim vectors matching the ``Vector(768)`` column). Cosine
similarity search via ``ivfflat`` index retrieves the most relevant chunks.

Each child links back to its parent via ``parent_id`` - the parent's
``chunk_text`` is returned to the LLM for generation context while the child
provides precise retrieval. This parent-child pattern gives +10-15% accuracy
over flat chunking (2025-2026 RAG benchmarks).

The ``embedding_model`` and ``embedding_dims`` columns record which model
produced the vector, enabling future re-embed migrations when upgrading
models or dimensions.
"""

from __future__ import annotations

import uuid
from datetime import datetime

from pgvector.sqlalchemy import Vector
from sqlalchemy import (
    DateTime,
    ForeignKey,
    ForeignKeyConstraint,
    Index,
    Integer,
    String,
    Text,
    func,
    text,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column

from ai_agent.models.base import Base


class AiRagChunkModel(Base):
    """One embedded child chunk (~400 tokens) for vector similarity search."""

    __tablename__ = "ai_rag_chunks"
    __table_args__ = (
        # Parent PK is composite (tenant_id, id) - the FK must be composite
        # too; a single-column FK to id alone would fail DDL on Postgres.
        ForeignKeyConstraint(
            ["tenant_id", "parent_id"],
            ["ai_rag_parents.tenant_id", "ai_rag_parents.id"],
            ondelete="CASCADE",
        ),
        Index("idx_rag_chunks_module", "tenant_id", "module"),
        Index("idx_rag_chunks_source", "tenant_id", "source_ref"),
    )

    tenant_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("tenants.id", ondelete="CASCADE"),
        primary_key=True,
        nullable=False,
    )
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, nullable=False
    )
    parent_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False)
    source_ref: Mapped[str] = mapped_column(Text, nullable=False)
    chunk_text: Mapped[str] = mapped_column(Text, nullable=False)
    embedding = mapped_column(Vector(768), nullable=False)
    module: Mapped[str] = mapped_column(String(100), nullable=False)
    chunk_index: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text("0"))
    metadata_: Mapped[dict[str, object]] = mapped_column(
        "metadata", JSONB, nullable=False, server_default=text("'{}")
    )
    embedding_model: Mapped[str] = mapped_column(String(100), nullable=False)
    embedding_dims: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text("768"))
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
